// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kt7756294

//@version=5
strategy("MACD,VWAP,SUPERTREND", overlay=true,max_labels_count=500,max_lines_count=500,max_boxes_count = 500,calc_on_every_tick = true)
fast_length = input(title="Fast Length", defval=12)
slow_length = input(title="Slow Length", defval=26) 
src = input(title="Source", defval=close)
signal_length = input.int(title="Signal Smoothing",  minval = 1, maxval = 50, defval = 9)
sma_source = input.string(title="Oscillator MA Type",  defval="EMA", options=["SMA", "EMA"])
sma_signal = input.string(title="Signal Line MA Type", defval="EMA", options=["SMA", "EMA"])
// Plot colors
col_macd = input(#2962FF, "MACD Line  ", group="Color Settings", inline="MACD")
col_signal = input(#FF6D00, "Signal Line  ", group="Color Settings", inline="Signal")
col_grow_above = input(#26A69A, "Above   Grow", group="Histogram", inline="Above")
col_fall_above = input(#B2DFDB, "Fall", group="Histogram", inline="Above")
col_grow_below = input(#FFCDD2, "Below Grow", group="Histogram", inline="Below")
col_fall_below = input(#FF5252, "Fall", group="Histogram", inline="Below")
// Calculating
fast_ma = sma_source == "SMA" ? ta.sma(src, fast_length) : ta.ema(src, fast_length)
slow_ma = sma_source == "SMA" ? ta.sma(src, slow_length) : ta.ema(src, slow_length)
//Supertrend
atrPeriod = input(20, "ATR Length")
factor = input.float(2, "Factor", step = 0.01)

macd = fast_ma - slow_ma
signal = sma_signal == "SMA" ? ta.sma(macd, signal_length) : ta.ema(macd, signal_length)
hist = macd - signal
// slope1=str.tostring((macd-macd[5])/5, "#.##")
// slope2=str.tostring((signal-signal[5])/5,"#.##")
// label.new(bar_index,high,str.tostring(macd,"#.##") + " " + str.tostring(ta.vwap) + " "+slope2 ,textcolor = color.white)
// math.atan(ta.change(macd)/signal)
// vwapDifference=ta.vwap - close
[_, direction] = ta.supertrend(factor, atrPeriod)

buy  = ta.crossover(macd, signal) and hist > 0 and ta.vwap > open 
supertrendBuyCondition= (buy and  ( ta.change(direction) < 0 or ta.change(direction[1]) < 0 or ta.change(direction[2]) < 0 ) )   or ( ta.change(direction)<0 and ( buy[1] or buy [2] ))
timeBuyCondition= supertrendBuyCondition and time>=1400
sell = ta.crossunder(macd, signal) or ta.change(direction) >0
// label.new(bar_index,high,str.tostring(buy))

plotchar(timeBuyCondition,char="Buy",color=color.green ,location= location.belowbar)
plotchar(sell,char="Sell",color=color.red,location= location.belowbar)

// hline(0, "Zero Line", color=color.new(#787B86, 50))

// plot(hist, title="Histogram", style=plot.style_columns, color=(hist>=0 ? (hist[1] < hist ? col_grow_above : col_fall_above) : (hist[1] < hist ? col_grow_below : col_fall_below)))
// plot(macd, title="MACD", color=col_macd)
// plot(signal, title="Signal", color=col_signal)
if timeBuyCondition
    strategy.entry("buy",direction = strategy.long)
if sell
    strategy.close("buy")



if ta.change(direction) < 0 and time(timeframe.period, "0930-1400:23456")
    label.new(bar_index,high,'Buy',textcolor=color.white)

if ta.change(direction) > 0
    label.new(bar_index,high,'Sell',textcolor=color.white)
plot(ta.vwap,color=color.blue)
time(timeframe.period,"1600-2000")
t1 = time(timeframe.period, "0930-1400:23456")
bgcolor(t1 ? color.new(color.blue, 90) : na)
// label.new(bar_index,low-10,str.tostring(timeframe.period))